# see https://github.com/serverless/serverless/tree/master/docs/01-guide

service: nightbear-api

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET greet

custom:
  writeEnvVars:
    NIGHTBEAR_API_DB_URL: ${env:NIGHTBEAR_API_DB_URL}

plugins:
   - serverless-plugin-write-env-vars
