# see https://github.com/serverless/serverless/tree/master/docs/01-guide
service: nightbear-api

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

# see https://github.com/serverless/serverless/blob/master/docs/02-providers/aws/events/01-apigateway.md
functions:
  status:
    handler: lambda.status
    events:
      - http: GET status
  test:
    handler: lambda.test
    events:
      - http: GET test
      - http: POST test

# see https://www.npmjs.com/package/serverless-plugin-write-env-vars
custom:
  writeEnvVars:
    NIGHTBEAR_API_ENV: ${env:NIGHTBEAR_API_ENV}
    NIGHTBEAR_API_VERSION: ${env:NIGHTBEAR_API_VERSION}
    NIGHTBEAR_API_DB_URL: ${env:NIGHTBEAR_API_DB_URL}
    NIGHTBEAR_API_LOG_LEVEL: ${env:NIGHTBEAR_API_LOG_LEVEL}
    NIGHTBEAR_API_PAPERTRAIL_URL: ${env:NIGHTBEAR_API_PAPERTRAIL_URL}

plugins:
   - serverless-plugin-write-env-vars
