# see https://github.com/serverless/serverless/tree/master/docs/01-guide
service: nightbear-api

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

# see https://github.com/serverless/serverless/blob/master/docs/02-providers/aws/events/01-apigateway.md
functions:
  hello:
    handler: handler.status
    events:
      - http: GET status
      - http: POST status

# see https://www.npmjs.com/package/serverless-plugin-write-env-vars
custom:
  writeEnvVars:
    NIGHTBEAR_API_DB_URL: ${env:NIGHTBEAR_API_DB_URL}

plugins:
   - serverless-plugin-write-env-vars
